### ISSUE TITLE
add metadata to Parameter schema

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/scabha2#6]
Use case for @JSKenyon: checking that all elements of a list have appropriate values

```
select_corr:
  dtype: List[int]
  metadata:
    element_choices: [0,1,2,3]
```

Note how this is not the same thing as ``choices`` in the normal schema.
